#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const pkg = JSON.parse(fs.readFileSync(path.resolve(__dirname, '..', 'package.json'), 'utf-8'));
const out = path.resolve(__dirname, '..', 'src', 'version.ts');

fs.writeFileSync(out, `// Auto-generated by scripts/gen-version.js — do not edit\nexport const VERSION = '${pkg.version}';\n`);
